export const USER_STATUSES = {
   IN_THE_PROCESS_OF_REGISTRATION: 'IN_THE_PROCESS_OF_REGISTRATION',
   ACTIVE: 'ACTIVE',
   BANNED: 'BANNED'
};

export const USER_ROLES = {
   CLIENT: 'CLIENT',
   MANAGER: 'MANAGER',
}

export const USER_GENDERS = {
   MALE: 'MALE',
   FEMALE: 'FEMALE',
};

export const USER_COUNTRIES = {
   GREAT_BRITAIN: 'GREAT_BRITAIN',
   LATVIA: 'LATVIA',
   LITHUANIA: 'LITHUANIA',
   MOLDOVA: 'MOLDOVA',
   GERMANY: 'GERMANY',
   POLAND: 'POLAND',
   ROMANIA: 'ROMANIA',
   USA: 'USA',
   TURKEY: 'TURKEY',
   UKRAINE: 'UKRAINE',
   FRANCE: 'FRANCE',
}

export const ERROR_MESSAGES = {
   FORBIDDEN: 'FORBIDDEN',
   UNAUTHORIZED: 'UNAUTHORIZED',
   NO_ACCESS_RIGHTS: 'NO ACCESS RIGHTS',
   USER_NOT_FOUND: 'USER NOT FOUND',
   LOGIN_ALREADY_EXISTS: 'LOGIN ALREADY EXISTS',
   EMAIL_ALREADY_EXISTS: 'EMAIL ALREADY EXISTS',
}